version: "3.9"

services:
  necesse:
    container_name: Necesse-Server
    image: necesse-server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./necesse_data:/root/.config/Necesse
    restart: unless-stopped
    ports:
      - 14159-14159:14159-14159/udp
    envfile:
      - env
